#!/usr/bin/env python3
"""Validate functional-test input files for parser-visible mistakes."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
FUNCTIONAL = ROOT / "tests" / "functional"


def section_lines(path: Path) -> dict[str, dict[str, tuple[int, str]]]:
    sections: dict[str, dict[str, tuple[int, str]]] = {}
    current = ""
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip().lower()
            sections.setdefault(current, {})
            continue
        if "=" in line and current:
            key, value = line.split("=", 1)
            sections.setdefault(current, {})[key.strip().lower()] = (lineno, value.strip())
    return sections


def parse_bool_pair(value: str) -> tuple[bool, bool] | None:
    parts = [part.strip().lower() for part in value.split(",")]
    if len(parts) != 2:
        return None
    try:
        return tuple(part in {".true.", "true", "t", "1"} for part in parts)  # type: ignore[return-value]
    except ValueError:
        return None


def key_value(section: dict[str, tuple[int, str]], key: str, default: str = "") -> str:
    return section.get(key, (0, default))[1].strip().lower()


def expected_checkpoint_layout(path: Path) -> str | None:
    """Layout of the checkpoint this case restarts from, or None if unknowable.

    Deliberately inferred from the *producing input*, not from files on disk.
    The checkpoints are generated by the sibling run that precedes this one in
    the suite and are not tracked, so a clean checkout has none of them — an
    earlier version of this check globbed for `domain1_flow_restart_*.bin`,
    passed locally where previous runs had left them behind, and failed on a
    pristine clone, which is what CI measures.
    """
    siblings = [
        sibling
        for sibling in sorted(path.parent.parent.glob("*/input_chapsim.ini"))
        if sibling != path
    ]
    layouts = set()
    for sibling in siblings:
        io = section_lines(sibling).get("io", {})
        written = key_value(io, "restart_data_layout_write") or key_value(
            io, "restart_data_layout"
        )
        if written:
            layouts.add(written)
    # Only decide when the producers agree; an ambiguous setup is not this
    # checker's to adjudicate.
    return layouts.pop() if len(layouts) == 1 else None


def main() -> int:
    errors: list[str] = []
    for path in sorted(FUNCTIONAL.rglob("*.ini")):
        sections = section_lines(path)
        domain = sections.get("domain", {})
        if "domain" in sections and "lyt" not in domain:
            errors.append(f"{path.relative_to(ROOT)}: [domain] missing required key lyt")
        if "yt" in domain:
            lineno, _ = domain["yt"]
            errors.append(f"{path.relative_to(ROOT)}:{lineno}: use lyt, not yt")

        thermo = sections.get("thermo", {})
        gravity = thermo.get("igravity")
        if gravity is not None:
            lineno, value = gravity
            if len([part for part in value.split(",") if part.strip()]) != 3:
                errors.append(
                    f"{path.relative_to(ROOT)}:{lineno}: igravity must contain three comma-separated components"
                )

        probe = sections.get("probe", {})
        npp_entry = probe.get("npp")
        if npp_entry is None:
            continue
        try:
            npp = int(npp_entry[1].split(",", 1)[0])
        except ValueError:
            errors.append(f"{path.relative_to(ROOT)}:{npp_entry[0]}: invalid npp value")
            continue
        for i in range(1, npp + 1):
            key = f"pt{i}"
            if key not in probe:
                errors.append(f"{path.relative_to(ROOT)}: [probe] missing required key {key}")
            else:
                lineno, value = probe[key]
                if len([part for part in value.split(",") if part.strip()]) != 3:
                    errors.append(f"{path.relative_to(ROOT)}:{lineno}: {key} must contain three comma-separated coordinates")

        io = sections.get("io", {})
        read_pair = parse_bool_pair(key_value(io, "is_record_xoutlet_read_xinlet"))
        if read_pair is None or not read_pair[1]:
            continue

        data_dir = path.parent / "1_data"
        if not data_dir.is_dir():
            continue

        has_bundled_zero = (data_dir / "domain1_xoutlet_database_0.bin").exists()
        has_per_field_50 = (data_dir / "domain1_outlet1_qx_50.bin").exists()
        if has_per_field_50 and not has_bundled_zero:
            layout_read = key_value(io, "restart_data_layout_read") or key_value(io, "restart_data_layout")
            offset = key_value(io, "ndb_file_offset", "0")

            # restart_data_layout_read drives three reads in io_restart.f90: the
            # flow checkpoint (line 1187), the thermo checkpoint (line 1434) and
            # the inlet database (line 2685). Only the inlet-database read has a
            # fallback — if no bundled database file is there it reads per-field
            # and warns. The two checkpoint reads abort.
            #
            # So a case may legitimately declare `bundled` while shipping a
            # per-field inlet database, provided its checkpoint is bundled: the
            # key is set for the checkpoint and the database takes the fallback.
            # Demanding `per_field` here would break the checkpoint read, which
            # is what this check used to do.
            restarts = (
                key_value(sections.get("flow", {}), "initfl") == "restart"
                or key_value(sections.get("thermo", {}), "inittm") == "restart"
            )
            expected = expected_checkpoint_layout(path)
            if restarts and expected is not None and layout_read != expected:
                errors.append(
                    f"{path.relative_to(ROOT)}: restart_data_layout_read is "
                    f"{layout_read or 'bundled (default)'} but the checkpoint it "
                    f"restarts from is written {expected}; the checkpoint read "
                    "has no fallback and would abort"
                )

            if offset != "50":
                errors.append(
                    f"{path.relative_to(ROOT)}: reads *_50 inlet database, so ndb_file_offset must be 50"
                )

    if errors:
        raise AssertionError("\n".join(errors))

    print("Functional .ini checks OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
