"""
README
-------
## Overview

This script generates plots from two monitoring log files generated by CHAPSim2:
1. domain1_monitor_bulk_history.log (columns: time, MKE, ux_bulk)
2. domain1_monitor_change_history.log (columns: time, mass_conservation[1,2,3], dm/dt, dtke/dt)

## Features:
- Skips first 3 header lines from both files
- Plots every 10th data point to reduce density
- Creates 5 subplots in a single figure:
    * MKE vs time
    * ux_bulk vs time
    * Mass conservation components vs time
    * dm/dt vs time
    * dtke/dt vs time
- Saves the figure as 'monitor_history.png' in high resolution (300 DPI)

## Usage:
1. Ensure the following data structure:
   - ../3_monitor/: Contains both log files and this script.
2. Run: 
```
python3 plot_monitor_bulk_change_history.py

## Dependencies:
- numpy
- matplotlib

Author: W Wang (STFC)
"""

import numpy as np
import matplotlib.pyplot as plt

# Set white background and black edges
plt.rcParams['figure.facecolor'] = 'white'
plt.rcParams['axes.facecolor'] = 'white'
plt.rcParams['savefig.facecolor'] = 'white'
plt.rcParams['axes.edgecolor'] = 'black'
plt.rcParams['axes.labelcolor'] = 'black'
plt.rcParams['xtick.color'] = 'black'
plt.rcParams['ytick.color'] = 'black'

# Read the data from the files, skipping first 3 lines
bulk_data = np.loadtxt('domain1_monitor_bulk_history.log', skiprows=3)
mass_data = np.loadtxt('domain1_monitor_change_history.log', skiprows=3)

# Extract data from bulk_data (using every 10th point)
time_bulk = bulk_data[::10, 0]
MKE = bulk_data[::10, 1]
ux_bulk = bulk_data[::10, 2]

# Extract data from mass_data (using every 10th point)
time_mass = mass_data[::10, 0]
mass_cons_1 = mass_data[::10, 1]
mass_cons_2 = mass_data[::10, 2]
mass_cons_3 = mass_data[::10, 3]
dmdt = mass_data[::10, 4]
dtkedt = mass_data[::10, 5]

# Create figure with subplots
plt.style.use('bmh')
fig = plt.figure(figsize=(15, 12))

# Plot 1: MKE
ax1 = plt.subplot(3, 2, 1)
ax1.plot(time_bulk, MKE, 'b-', label='MKE')
ax1.set_xlabel('Time')
ax1.set_ylabel('MKE')
ax1.grid(True, color='gray', alpha=0.3)
ax1.legend()

# Plot 2: ux_bulk
ax2 = plt.subplot(3, 2, 2)
ax2.plot(time_bulk, ux_bulk, 'r-', label='ux_bulk')
ax2.set_xlabel('Time')
ax2.set_ylabel('ux_bulk')
ax2.grid(True, color='gray', alpha=0.3)
ax2.legend()

# Plot 3: Mass Conservation Components
ax3 = plt.subplot(3, 2, 3)
ax3.plot(time_mass, mass_cons_1, 'b-', label='mass_cons[1]')
ax3.plot(time_mass, mass_cons_2, 'r-', label='mass_cons[2]')
ax3.plot(time_mass, mass_cons_3, 'g-', label='mass_cons[3]')
ax3.set_yscale('log')
ax3.set_xlabel('Time')
ax3.set_ylabel('Mass Conservation')
ax3.grid(True, color='gray', alpha=0.3)
ax3.legend()

# Plot 4: dm/dt
ax4 = plt.subplot(3, 2, 4)
ax4.plot(time_mass, dmdt, 'purple', label='dm/dt')
ax4.set_xlabel('Time')
ax4.set_ylabel('dm/dt')
ax4.grid(True, color='gray', alpha=0.3)
ax4.legend()

# Plot 5: dtke/dt
ax5 = plt.subplot(3, 2, 5)
ax5.plot(time_mass, dtkedt, 'orange', label='dtke/dt')
ax5.set_xlabel('Time')
ax5.set_ylabel('dtke/dt')
ax5.grid(True, color='gray', alpha=0.3)
ax5.legend()

# Adjust layout and add title
plt.tight_layout()
fig.suptitle('Monitor Variables History', fontsize=16, y=1.02)

# Save the plot
plt.savefig('monitor_history.png', bbox_inches='tight', dpi=300)
