blank_issues_enabled: false
contact_links:
  - name: CHAPSim Documentation
    url: https://github.com/CCP-NTH/CHAPSim2/tree/master/docs
    about: Check our documentation for answers to common questions
  - name: CFD Code Discussions
    url: https://github.com/CCP-NTH/CHAPSim2/discussions
    about: Please use discussions for feature ideas and broader topics
