"""
README:
-------
This script is designed to plot monitor point data generated by CHAPSim2.
It reads and visualizes time series data for multiple variables (u, v, w, p, phi)
from monitor points, with optional temperature data for thermal cases.

Features:
- Plots multiple monitor points with different markers and colors
- Handles both isothermal and thermal flow cases
- Skips every M points for clearer visualization
- Optionally starts plotting from a user-given x-axis value
- Saves high-resolution PNG output

Data format:
- The data and this script should be stored in the folder ./3_monitor/
- Files should be named: domain1_monitor_ptX_flow.dat (where X is the point number)
- Each file contains columns: time, u, v, w, p, phi, [T]
  or iteration, time, u, v, w, p, phi, [T]
- First 3 lines are skipped (header)

Usage:
1. Ensure the following data structure:
   - ../3_monitor/: Contains both monitor point data files and this script.
2. Run: python3 plot_monitor_points.py

Author: W Wang (STFC)
"""

import numpy as np
import matplotlib.pyplot as plt
import argparse
import os
import sys
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description="Plot CHAPSim2 monitor point histories.")
    parser.add_argument("--case-dir", default=None, help="Case directory containing 3_monitor/.")
    parser.add_argument(
        "--monitor-dir",
        "--input-dir",
        dest="monitor_dir",
        default=None,
        help="Directory containing domain*_monitor_pt*_flow.dat files.",
    )
    parser.add_argument("--output-dir", default=None, help="Directory for monitor_points_plot.png.")
    parser.add_argument("--domain-id", type=int, default=1, help="Domain id used in monitor filenames.")
    parser.add_argument("--num-points", type=int, default=None, help="Number of monitor points to plot.")
    parser.add_argument("--stride", type=int, default=None, help="Plot every Nth sample.")
    parser.add_argument("--xmin", "--x-min", dest="x_min", default=None, help="Only plot samples with time >= this value.")
    return parser.parse_args()


def resolve_monitor_dir(args) -> Path:
    if args.monitor_dir is not None:
        return Path(args.monitor_dir).resolve()
    if args.case_dir is not None:
        return (Path(args.case_dir) / "3_monitor").resolve()
    return Path.cwd()

def read_monitor_data(filename):
    """Read data from monitor point file."""
    if not os.path.exists(filename):
        print(f"File {filename} not found")
        return None
        
    try:
        with open(filename, "r", encoding="utf-8") as f:
            header = "".join(f.readline() for _ in range(3)).lower()

        has_iteration_column = "iteration" in header
        time_col = 1 if has_iteration_column else 0
        first_var_col = time_col + 1

        data = np.genfromtxt(filename, skip_header=3)
        if data is None or len(data) == 0:
            print(f"No data read from {filename}")
            return None

        data = np.atleast_2d(data)
        required_cols = first_var_col + 5
        if data.shape[1] < required_cols:
            print(f"Not enough columns in {filename}; expected at least {required_cols}")
            return None

        return data, time_col, first_var_col
    except Exception as e:
        print(f"Error reading {filename}: {str(e)}")
        return None

def plot_monitor_points(N, M, x_min=None, monitor_dir=Path("."), output_dir=None, domain_id=1):
    """Plot monitor points data for N points."""
    print("\nStarting to plot monitor points...")
    monitor_dir = Path(monitor_dir)
    output_dir = Path(output_dir) if output_dir is not None else monitor_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create figure with subplots
    variables = ['u', 'v', 'w', 'p', 'phi']
    fig, axes = plt.subplots(len(variables), 1, figsize=(12, 15), sharex=True)
    fig.suptitle('Monitor Points Data')
    
    # Colors for different monitor points
    colors = plt.cm.rainbow(np.linspace(0, 1, N))
    
    # Different marker styles for variety
    markers = ['o', 's', '^', 'v', 'D', 'p', 'h', '8']
    
    data_found = False  # Flag to check if any data was successfully plotted
    successful_files = []  # List to store successfully plotted files
    
    for i in range(1, N+1):
        filename = monitor_dir / f'domain{domain_id}_monitor_pt{i}_flow.dat'
        monitor_data = read_monitor_data(filename)
        if monitor_data is None:
            continue

        data, time_col, first_var_col = monitor_data
        if x_min is not None:
            data = data[data[:, time_col] >= x_min]
            if data.size == 0:
                print(f"No data in {filename} for x >= {x_min}")
                continue
            
        data_found = True
        successful_files.append(filename)
        print(f"Successfully reading data from: {filename}")
        
        # Apply the requested sampling interval.
        time = data[::M, time_col]
        
        # Plot each variable
        for j, var in enumerate(variables):
            axes[j].plot(time, data[::M, first_var_col+j], 
                        marker=markers[i % len(markers)],  # Cycle through markers
                        linestyle='none',  # No lines between points
                        label=f'Point {i}', 
                        color=colors[i-1],
                        markersize=4)  # Smaller markers for clarity
            axes[j].set_ylabel(f'{var}')
            axes[j].grid(True)
            axes[j].legend()
    
    if not data_found:
        print("\nNo valid data found for any monitor point")
        plt.close()
        return
        
    # Set xlabel for bottom subplot
    axes[-1].set_xlabel('Time')
    
    plt.tight_layout()
    output_path = output_dir / "monitor_points_plot.png"
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"\nPlot saved as '{output_path}'")
    print(f"\nSuccessfully plotted {len(successful_files)} files:")
    for file in successful_files:
        print(f"- {file}")
    plt.close()

def parse_optional_x_min(value):
    """Return a float lower x-axis bound, or None when left blank."""
    if value is None:
        return None
    value = value.strip()
    if not value:
        return None
    value = value.replace("x", "").replace(">", "").replace("=", "").strip()
    return float(value)

if __name__ == "__main__":
    args = parse_args()
    monitor_dir = resolve_monitor_dir(args)
    output_dir = Path(args.output_dir).resolve() if args.output_dir is not None else monitor_dir
    N = args.num_points
    M = args.stride
    if N is None:
        N = int(input("Enter the number of monitor points to plot: "))
    if M is None:
        M = int(input("Enter sampling interval (skip every M points for clearer visualization): "))

    if N <= 0:
        raise ValueError("--num-points must be a positive integer.")
    if M <= 0:
        raise ValueError("--stride must be a positive integer.")

    if args.x_min is not None:
        x_min = parse_optional_x_min(args.x_min)
    elif sys.stdin.isatty() and args.num_points is None and args.stride is None:
        x_min = parse_optional_x_min(
            input("Enter lower x-axis value to plot from, e.g. 50 or x>50 [all]: ")
        )
    else:
        x_min = None

    plot_monitor_points(N, M, x_min, monitor_dir=monitor_dir, output_dir=output_dir, domain_id=args.domain_id)
